[package]
name = "pi_multimedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
pi_assets = "0.7"
pi_atom = "0.1"
pi_share = "0.1"
pi_async = "0.2"
pi_async_common = {git="https://github.com/GaiaWorld/pi_async_common.git"}
lazy_static = "1.4"
log = "0.4"