[package]
name = "pi_hal"
version = "0.1.0"
edition = "2021"
authors = ["yineng <yineng@gmail.com>"]
description = "Front end cross platform packaging"
repository = "https://github.com/GaiaWorld/pi_hal.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "hal"]

[dependencies]
image = "0.23"
pi_assets = "0.8"
pi_atom = "0.2"
pi_share = "0.4"
pi_async = "0.4"
pi_hash = "0.1"
pi_slotmap = {version= "0.1", features = ["serde"]}
pi_ucd="0.1"
ordered-float="3.0"
nalgebra = "0.31"
lazy_static = "1.4"
num_cpus = "1.13"
log = "0.4"
serde = { version = "1.0", features = ["derive"], option=true }
derive_deref = "1.1"
async-trait = "0.1"
parking_lot = "0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
font_kit = {git="http://ser.yinengyun.com:10082/tech/font_kit.git"}


[features]
empty=[]

